[package]
name = "pvp-game-dilapidation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.36.0", features = ["ttf", "image", "mixer"] }
component-macro = { version = "0.1.0", path = "./component-macro" }
reqwest = { version = "0.12.4", features = ["blocking"] }
